### ISSUE TITLE
TODO list before CRAN submission

### ISSUE THREAD

**Issue by walkerke** [walkerke/idbr#2]
There are still a few more things to do before this package is ready for CRAN: 
- [x] Better error handling for unavailable years (see https://github.com/walkerke/idbr/issues/1)
- [x] Complete the documentation with examples
- [x] Add option to install the API key to the user's .Rprofile so that `idb_api_key()` doesn't need to be called every time (which will remain the default, however).

**Comment by walkerke** [comment]
Docs are complete; I've added better error handling as well, and I'll look to improve upon this even more in the future.  Advanced users can modify their .Rprofile themselves if they want to; I'll add a note in the README about how to do this.
